#!/bin/bash
#set -x

TOPDIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)

TESTLIB_PATH="$TOPDIR/lib"

# Then as many as the sub-libraries as you need
. ${TESTLIB_PATH}/core.sh
. ${TESTLIB_PATH}/git.sh
. ${TESTLIB_PATH}/centosrepo.sh
. ${TESTLIB_PATH}/xen-advisory.sh

# And do your own thing rather than running commands
# I suggest defining a "main" function of your own and running it like this.
cmdline "$@"
